# See: https://www.dartlang.org/tools/pub/pubspec
name: foobar
version: 0.0.0
description: >-
  TODO for Dart (60-180 characters)
author: Arto Bendiken <arto@bendiken.net>
homepage: https://github.com/drydart/foobar
documentation:
dependencies:
  meta: ^1.1.6
dev_dependencies:
  test: any
dependency_overrides:
environment:
  sdk: '>=2.1.0 <3.0.0'
executables:
publish_to: none
