PACKAGE :=
VERSION := $(shell cat VERSION)

SOURCES :=

TARGETS :=

all: $(TARGETS)

check:
	@echo "not implemented"; exit 2 # TODO

dist:
	@echo "not implemented"; exit 2 # TODO

install:
	@echo "not implemented"; exit 2 # TODO

clean:
	@rm -f *~ $(TARGETS)

distclean: clean

mostlyclean: clean

.PHONY: check dist install clean distclean mostlyclean
